In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,2,3],[4,5,6],[7,8,20]
])
b = np.array([
    [10],
    [11],
    [20]
])

In [44]:
def gauss_algo(a,b):

    ####- Checking if the matrix a is a square matrix -####
    if a.shape[0] != a.shape[1]:
        print('Matrix a is not a square matrix hence cannot proceed')
        print('\n')
        return
    ####- Checking if the number of rows between matrix a and b are same -####
    if a.shape[0] != b.shape[0]:
        print('Matrix a and matrix b dont have the same number of rows')
        print('\n')
        return

    ### Creating an augmented matrix ####

    aug = np.concatenate((a,b),axis=1)
    print('Augmented matrix created successfully')
    print(aug)
    print('\n')

    ### Forward elimination - creating a UL ( Upper triangle) ####
    # First checking if first pivot is non-zero
    if np.isclose(aug[0][0],0):
        print('---------------------------------------------------------------')
        print('First pivot is 0 \ncannot continue...\nrow pivoting required')
        print('---------------------------------------------------------------')
        print('\n')
        return
    ### Starting Gauss Elimination #####
    n = b.shape[0] ## 3 

    for j in range(0,n):
        for i in range(j+1,n): 
            aug[i] = aug[i] - ((aug[i][j])/(aug[j][j]))*aug[j]
            print('\n')
            print('Working on row echelon form....')
            print(aug)
    print('\n')
    print('Matrix has been reduced to row echelon form')
    print(aug)

    ### Starting Backward substitution #####
    x = np.zeros(3)
    print(x)
    
    x[n-1] = aug[n-1][n]/aug[n-1][n-1]
    
    
    for i in range(n - 1, -1, -1):
        x[i] = (aug[i][n] - sum(aug[i][j] * x[j]
                for j in range(i + 1, n))) / aug[i][i]
    print("\nSolution for the system:")
    for xi in x:
        print(f"{xi:.8f}")

In [45]:
aug = gauss_algo(a,b)

Augmented matrix created successfully
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8 20 20]]




Working on row echelon form....
[[  1   2   3  10]
 [  0  -3  -6 -29]
 [  7   8  20  20]]


Working on row echelon form....
[[  1   2   3  10]
 [  0  -3  -6 -29]
 [  0  -6  -1 -50]]


Working on row echelon form....
[[  1   2   3  10]
 [  0  -3  -6 -29]
 [  0   0  11   8]]


Matrix has been reduced to row echelon form
[[  1   2   3  10]
 [  0  -3  -6 -29]
 [  0   0  11   8]]
[0. 0. 0.]

Solution for the system:
-8.60606061
8.21212121
0.72727273
